language: python
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python api_server.py &
  - sleep 2
  - python -m unittest tests.format tests.functional tests.negative
